<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Report PDF</title>
    <style>
        body {
            font-family: DejaVu Sans, sans-serif;
            color: #333;
        }
        .header {
            text-align: center;
            margin-bottom: 20px;
        }
        .title {
            font-size: 24px;
            font-weight: bold;
        }
        .section {
            margin-bottom: 15px;
        }
        .label {
            font-weight: bold;
        }
        .box {
            border: 1px solid #ddd;
            padding: 10px;
            border-radius: 5px;
        }
        .footer {
            margin-top: 30px;
            text-align: right;
            font-size: 12px;
            color: #777;
        }
    </style>
</head>
<body>

<div class="header">
    <div class="title">Report Details</div>
</div>

<div class="section box">
    <p><span class="label">Report Name:</span> {{ $report->report_name }}</p>
    <p><span class="label">Status:</span> {{ ucfirst($report->status) }}</p>
    <p><span class="label">Generated By:</span> {{ $report->user->full_name ?? 'N/A' }}</p>
    <p><span class="label">Date:</span> {{ $report->created_at->format('Y-m-d') }}</p>
</div>

<div class="section box">
    <p><span class="label">Description:</span></p>
    <p>{{ $report->description ?? 'No description available.' }}</p>
</div>

<div class="footer">
    Generated on: {{ now()->format('Y-m-d H:i:s') }}
</div>

</body>
</html>