@include('components.header')
@include('components.sidebar')
<div class="main-container">
    @if(session('error'))
    <div class="alert alert-danger">
        <span>{{ session('error') }}</span>
        <button type="button" onclick="this.parentElement.remove()">×</button>
    </div>
    @endif

    @if(session('success'))
    <div class="alert alert-success">
        <span>{{ session('success') }}</span>
        <button type="button" onclick="this.parentElement.remove()">×</button>
    </div>
    @endif
    <div class="page-header">
        <h1>Reports</h1>
        <div class="page-actions">
            <button><i class="fas fa-download"></i> Generate Report</button>
        </div>
    </div>

    <div class="grid-container">
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Project Completion Rate</h3>
                <i class="fas fa-chart-pie"></i>
            </div>
            <div class="card-value">{{ $projectCompletionRate }}%</div>
            <p class="card-description">Average completion rate across all projects</p>
        </div>
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Employee Performance</h3>
                <i class="fas fa-chart-bar"></i>
            </div>
            <div class="card-value">Excellent</div>
            <p class="card-description">Overall team performance rating</p>
        </div>
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Budget Utilization</h3>
                <i class="fas fa-money-bill-wave"></i>
            </div>
            <div class="card-value">{{ $budgetUtilization }}%</div>
            <p class="card-description">Percentage of budget utilized</p>
        </div>
        <div class="card">
            <div class="card-header">
                <h3 class="card-title">Task Overdue Rate</h3>
                <i class="fas fa-exclamation-triangle"></i>
            </div>
            <div class="card-value">{{ $taskOverdueRate }}%</div>
            <p class="card-description">Percentage of tasks past due date</p>
        </div>
    </div>

    <div class="form-section">
        <h2>Generate Custom Report</h2>
        <form>
            <div class="grid-container" style="grid-template-columns: 1fr 1fr;">
                <div class="form-group">
                    <label for="reportType">Report Type</label>
                    <select id="reportType">
                        <option value="">Select Report Type</option>
                        <option value="project_summary">Project Summary</option>
                        <option value="employee_activity">Employee Activity</option>
                        <option value="financial_overview">Financial Overview</option>
                        <option value="attendance_summary">Attendance Summary</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="timePeriod">Time Period</label>
                    <select id="timePeriod">
                        <option value="this_month">This Month</option>
                        <option value="last_month">Last Month</option>
                        <option value="this_quarter">This Quarter</option>
                        <option value="last_quarter">Last Quarter</option>
                        <option value="this_year">This Year</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="startDate">Start Date (Optional)</label>
                    <input type="date" id="startDate">
                </div>
                <div class="form-group">
                    <label for="endDate">End Date (Optional)</label>
                    <input type="date" id="endDate">
                </div>
            </div>
            <div class="form-actions">
                <button type="submit" class="btn-primary">Generate Report</button>
                <button type="reset" class="btn-secondary">Clear</button>
            </div>
        </form>
    </div>

    <div class="table-container">
        <div class="card-header" style="padding: 15px 20px; border-bottom: 1px solid var(--border-color);">
            <h3 class="card-title">Recent Reports</h3>
        </div>
        <table class="data-table">
            <thead>
                <tr>
                    <th>Report Name</th>
                    <th>Generated By</th>
                    <th>Date</th>
                    <th>Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @forelse($reports as $report)
                <tr>
                    <td>{{ $report->report_name }}</td>
                    <td>{{ $report->full_name }}</td>
                    <td>{{ \Carbon\Carbon::parse($report->created_at)->format('Y-m-d') }}</td>
                    <td>
                        <span class="status-badge {{ $report->status == 'ready' ? 'completed' : 'pending' }}">
                            {{ ucfirst($report->status) }}
                        </span>
                    </td>
                    <td class="action-buttons">
                        <a href="{{ route('reports.download', $report->id) }}"
                            class="icon-button"
                            title="Download Report">
                            <i class="fas fa-download"></i>
                        </a>

                        <a href="{{ route('reports.view', $report->id) }}"
                            class="icon-button"
                            title="View Report">
                            <i class="fas fa-eye"></i>
                        </a>
                    </td>
                </tr>
                @empty
                <tr>
                    <td colspan="5" style="text-align:center;">No reports found</td>
                </tr>
                @endforelse
            </tbody>
        </table>
    </div>

    <div class="pagination-wrapper">
    {{ $reports->links('pagination::default') }}
</div>

</div>