@include('components.header')
@include('components.sidebar')

<div class="main-container">
    @if(session('error'))
    <div class="alert alert-danger">
        <span>{{ session('error') }}</span>
        <button type="button" onclick="this.parentElement.remove()">×</button>
    </div>
@endif

@if(session('success'))
<div class="alert alert-success">
    <span>{{ session('success') }}</span>
    <button type="button" onclick="this.parentElement.remove()">×</button>
</div>
@endif
    <!-- HEADER -->
    <div class="page-header">
        <h1>{{ $report->report_name }}</h1>
        <div class="page-actions">
            <a href="{{ route('reports.download', $report->id) }}" class="btn-primary">
                <i class="fas fa-download"></i> Download
            </a>
            <a href="{{ url()->previous() }}" class="btn-secondary">
                Back
            </a>
        </div>
    </div>

    <!-- REPORT WRAPPER -->
    <div class="card" style="max-width: 1100px; margin: auto; padding: 30px;">

        <!-- META ROW -->
        <div style="display: flex; justify-content: space-between; margin-bottom: 25px; border-bottom: 1px solid var(--border-color); padding-bottom: 15px;">

            <div>
                <small class="card-description">Generated By</small>
                <div style="font-weight: 600;">
                    {{ $report->user->full_name ?? 'System' }}
                </div>
            </div>

            <div>
                <small class="card-description">Generated On</small>
                <div style="font-weight: 600;">
                    {{ $report->created_at->format('d M Y, h:i A') }}
                </div>
            </div>

            <div>
                <small class="card-description">Status</small>
                <div>
                    <span class="status-badge {{ $report->status == 'ready' ? 'completed' : 'pending' }}">
                        {{ ucfirst($report->status) }}
                    </span>
                </div>
            </div>

        </div>

        <!-- REPORT INFO -->
        <div style="margin-bottom: 30px;">
            <h3 style="margin-bottom: 10px;">Report Information</h3>

            <div style="display: grid; grid-template-columns: 1fr 1fr; gap: 20px;">
                <div>
                    <small class="card-description">Report Type</small>
                    <div>
                        {{ ucwords(str_replace('_', ' ', $report->report_type)) }}
                    </div>
                </div>

                <div>
                    <small class="card-description">Time Period</small>
                    <div>
                        {{ $report->start_date ?? 'N/A' }} —
                        {{ $report->end_date ?? 'N/A' }}
                    </div>
                </div>
            </div>
        </div>

        <!-- REPORT CONTENT -->
        <div>
            <h3 style="margin-bottom: 10px;">Report Summary</h3>

            <div style="line-height: 1.9; font-size: 15px; color: var(--text-color);">
                {!! nl2br(e($report->summary ?? 'No summary available for this report.')) !!}
            </div>
        </div>

    </div>

</div>